### ISSUE TITLE
Wrong directory structure fo building the dataset 

### ISSUE THREAD

**Issue by Nadav1** [fanq15/Few-Shot-Object-Detection-Dataset#1]
The directory structure you write in the README doesn't work. The actual structure should be:
YOUR_PATH
    ├── code
    │     ├── training scripts
    │     ├── testing scripts
    │     ├── ...
    │ 
    └── fsod
          ├── all_images
          │       ├── part_1
          │       └── part_2
          |
          ├── fsod_train_df.pkl
          ├── fsod_test_df.pkl
          ├── train_converter.py
          └── test_converter.py

**Comment by Donkee** [comment]
Hello, do you konw what's the meaning about the 4 data of bbox in annotations?
It dosen't seem like corner coordinates.

**Comment by fanq15** [comment]
Thank you for your comment. I change the pkl path from "./fsod_train_df.pkl" to "./all_images/fsod_train_df.pkl" in the `converter.py` files.
