### ISSUE TITLE
mapping table

### ISSUE THREAD

**Issue by yyqgood** [fanq15/Few-Shot-Object-Detection-Dataset#10]
Hi, should you provide such a mapping table?
E.g:
coco_id_name_map={1: 'person', 2: 'bicycle', 3: 'car', 4: 'motorcycle', 5: 'airplane',...}

**Comment by fanq15** [comment]
The category mapping table is in the `json` file. You can find it in the `categories`. It's same as the COCO format.

**Comment by yyqgood** [comment]
@fanq15 
thanks |
