### ISSUE TITLE
Details of figures

### ISSUE THREAD

**Issue by MiniLisaBear** [fanq15/Few-Shot-Object-Detection-Dataset#11]
Hi, in figure 5,there are 3 depth-wise conv,what are the kernel size of the first two depth-wise convs?Is also 1x1?Can u tell me? Thx.

**Comment by fanq15** [comment]
In the Attention RPN (Fig. 5), there is only one 1x1 depth-wise convolution layer followed by the regular RPN module. 
We average pooling the support feature to 1x1xC size and use it as the kernel to slide on the query feature map in a depth-wise way. You can reference SiamRPN++ for the detail of this operation. (The description of this operation in our paper is not accurate. We will fix it in the final version.) The resulted feature map is sent to the regular RPN module to generate proposals.
