### ISSUE TITLE
About the Similarity

### ISSUE THREAD

**Issue by gaowq2017** [fanq15/Few-Shot-Object-Detection-Dataset#12]
Hi@fanq15, I am interest in your job and when open the code? I have some problems as follow:
 Computing the similarity about support and query feature map, in general, by the way that computing the the cosine distance then what's the adervantages about this paper way? what's the similar? a value or vector?

**Comment by fanq15** [comment]
The code will be released in April. There are lots of ways to calculate the distance between support and query, and the cosine distance is the simplest but effective way to evaluate the similarity. Our method provides a more powerful way to calculate the similarity in pixel-level, path-level, and global-level, while the cosine distance is only a global-level distance. And our experiment shows that the multi-level distance is more effective. The similarity is a value for each (query, support) pair.

**Comment by fanq15** [comment]
Hi, the detectron2 based FSOD code is released!
https://github.com/fanq15/FewX


gao <notifications@github.com> 于2020年3月30日周一 下午4:03写道：
