### ISSUE TITLE
code release

### ISSUE THREAD

**Issue by SUYEgit** [fanq15/Few-Shot-Object-Detection-Dataset#13]
When will you release the codes of experiments? I will appreciate your reply! Thanks.

**Comment by fanq15** [comment]
The code will be released in April.

**Comment by Pluto1314** [comment]
@fanq15 Hello, it's about to be May. When will your code be released? Thank you!

**Comment by jsxapril** [comment]
up~

**Comment by fanq15** [comment]
Hi, the detectron2 based FSOD code is released!
https://github.com/fanq15/FewX


Su Ye <notifications@github.com> 于2020年3月31日周二 下午4:27写道：
