### ISSUE TITLE
Question about the attention RPN module

### ISSUE THREAD

**Issue by SeanCheng1019** [fanq15/Few-Shot-Object-Detection-Dataset#14]
Hi, after reading your paper, I'm confusing that how the RPN use the similarity map to build the proposal generation?   In section 4.2.1 , the paper just says  the proposals are generated based on the attention feature map.  ( Is the same way as Siamrpn++ :  use a  1*1 conv to adjust the response map channel to fit the regression and classification task separatedly ?)

**Comment by fanq15** [comment]
After get the attention map, we use it as the input of the regular RPN to generate the proposals. There is a small bug in the old version. Please reference our new version.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: ChiEnCheng <notifications@github.com>
发送时间: Saturday, April 4, 2020 9:31:53 AM
收件人: fanq15/Few-Shot-Object-Detection-Dataset <Few-Shot-Object-Detection-Dataset@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [fanq15/Few-Shot-Object-Detection-Dataset] Question about the attention RPN module (#14)


Hi, after reading your paper, I'm confusing that how the RPN use the similarity map to build the proposal generation? In section 4.2.1 , the paper just says the proposals are generated based on the attention feature map. ( Is the same way as Siamrpn++ : use a 1*1 conv to adjust the response map channel to fit the regression and classification task separatedly ?)

―
