### ISSUE TITLE
can you share your codes?

### ISSUE THREAD

**Issue by DTW1004** [fanq15/Few-Shot-Object-Detection-Dataset#16]
hello, I have read your paper, it's amazing! Hoping to see your code someday! Thanks~

**Comment by fanq15** [comment]
It will be released this month. Now I have too many courses and assignments……

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: DTW1004 <notifications@github.com>
发送时间: Wednesday, April 8, 2020 5:31:31 PM
收件人: fanq15/Few-Shot-Object-Detection-Dataset <Few-Shot-Object-Detection-Dataset@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [fanq15/Few-Shot-Object-Detection-Dataset] can you share your codes? (#16)


hello, I have read your paper, it's amazing! Hoping to see your code someday! Thanks~

―

**Comment by ghost** [comment]
Hello, I'm very interested in your work which features attention RPN and multi-relation detector.And could you please release your source code?I want to dive deep into your implementation details and find out more.Look forward to your reply~
