### ISSUE TITLE
Question about Multi-Relation Detector

### ISSUE THREAD

**Issue by Yinyf0804** [fanq15/Few-Shot-Object-Detection-Dataset#18]
Thanks for your great paper. I have a question about the three types of relation in Multi-Relation Detector.  
I wonder if global realation means avgpooling the roi features and use cosine similarty to calculate the match score, but I don't know how to calculate the other two relations. Could please tell me the details about that?

**Comment by fanq15** [comment]
You can reference the supplementary material for more details: Appendix A: Implementation Details of MultiRelation Detector.

**Comment by Yinyf0804** [comment]
Thanks for your help!
