### ISSUE TITLE
Could you share the source code of paper "Few-Shot Object Detection with Attention-RPN and Multi-Relation Detector"

### ISSUE THREAD

**Issue by one23sunnyQQ** [fanq15/Few-Shot-Object-Detection-Dataset#2]
Hi, thanks for your shared Few-Shot-Object-Detection-Dataset. 
Could you share the source code of paper "Few-Shot Object Detection with Attention-RPN and Multi-Relation Detector"?

Waiting for your reply soon.  :)

**Comment by fanq15** [comment]
Thank you for your attention to our paper. We will release our code after
the paper is accepted as a conference paper.
We use https://github.com/roytseng-tw/Detectron.pytorch as our base code.
You could try it by yourself.

one23sunnyQQ <notifications@github.com> 于2019年9月16日周一 下午4:09写道：

**Comment by one23sunnyQQ** [comment]
@fanq15 , Thank you for your reply. I have another question to ask you.
Your paper "Few-Shot Object Detection with Attention-RPN and Multi-Relation Detector".
In Figure 4, before the RoI Pooling layer, how did the proposal boxe of support sample come from?

**Comment by zeevikal** [comment]
@fanq15 Hi, what is the current status of the following paper "Few-Shot Object Detection with Attention-RPN and Multi-Relation Detector"? is it already published, where? is there any available code? 
thanks!

**Comment by JustinhoCHN** [comment]
@fanq15 Congratulations this paper was published in cvpr2020. May I ask when you will release the code? Thank you!

**Comment by Jibanul** [comment]
@fanq15 Hi, any update on releasing the code?
