### ISSUE TITLE
Some bbox annotations are wrong

### ISSUE THREAD

**Issue by RookieHong** [fanq15/Few-Shot-Object-Detection-Dataset#21]
For example, in fsod_train.json, the annotation with id = 903, it's bbox = [387.0, 595.0, 26.0, 39.0], the height and width of corresponding image with image_id = 2019000000903 are 533 and 800, obviously the bbox is out of range.

There are a few wrong bbox annotations like this.

**Comment by fanq15** [comment]
I checked the annotation and the height and width of 2019000000903 are 800 and 533.
![image](https://user-images.githubusercontent.com/26087110/81473239-aa823680-922f-11ea-8847-088b8b97b55a.png)

**Comment by RookieHong** [comment]
Load the image data and you'll see the height and width of 2019000000903 are 533 and 800, and simply transposing the image doesn't work. I visualized the instances by cropping them and found that the cropped images contain nothing... I suggest that you visualize more wrong bbox annotations and you will find out. You can find these wrong bbox annotations by checking if the cropped images' height and width match the ones in bbox annotations.

**Comment by RookieHong** [comment]
I guess this happens to those images whose actual height and width do not match the ones in annotations. I visualized some of them, and you can see that simply transposing the images may avoid out of range errors, but the boxes are not correct.
![image](https://user-images.githubusercontent.com/20601380/81476735-0ce63180-9246-11ea-8fdd-62cda74fc2ff.png)
![image](https://user-images.githubusercontent.com/20601380/81476767-356e2b80-9246-11ea-9e1d-c16a084f8667.png)
![image](https://user-images.githubusercontent.com/20601380/81476783-55055400-9246-11ea-85f0-84a52c3799ee.png)

**Comment by fanq15** [comment]
Thank you for your report! I will check it again and fix it.

**Comment by Lancelot365** [comment]
This is due to PIL not reading the transpose tag in EXIF. You can check the detectron2 code on loading images with pillow and reading exif transposing. The first image is a typical example from openimages.

**Comment by RookieHong** [comment]
Thanks for the EXIF problem, which I have been ignored for all time, using the codes from detectron2 below can read images correctly.
`def read_image(file_name, format=None):
    """
    Read an image into the given format.
    Will apply rotation and flipping if the image has such exif information.
    Args:
        file_name (str): image file path
        format (str): one of the supported image modes in PIL, or "BGR" or "YUV-BT.601"
    Returns:
        image (np.ndarray): an HWC image in the given format, which is 0-255, uint8 for
            supported image modes in PIL or "BGR"; float (0-1 for Y) for YUV-BT.601.
    """
    with PathManager.open(file_name, "rb") as f:
        image = Image.open(f)

        # capture and ignore this bug: https://github.com/python-pillow/Pillow/issues/3973
        try:
            image = ImageOps.exif_transpose(image)
        except Exception:
            pass

        return convert_PIL_to_numpy(image, format)`
But as I said above, simply transposing the image doesn't work, the annotations are indeed wrong.

**Comment by RookieHong** [comment]
Thanks for the EXIF problem, which I have been ignored for all time, using the codes from detectron2 below can read images correctly.
`def read_image(file_name, format=None):
    """
    Read an image into the given format.
    Will apply rotation and flipping if the image has such exif information.
    Args:
        file_name (str): image file path
        format (str): one of the supported image modes in PIL, or "BGR" or "YUV-BT.601"
    Returns:
        image (np.ndarray): an HWC image in the given format, which is 0-255, uint8 for
            supported image modes in PIL or "BGR"; float (0-1 for Y) for YUV-BT.601.
    """
    with PathManager.open(file_name, "rb") as f:
        image = Image.open(f)

        # capture and ignore this bug: https://github.com/python-pillow/Pillow/issues/3973
        try:
            image = ImageOps.exif_transpose(image)
        except Exception:
            pass

        return convert_PIL_to_numpy(image, format)`
But as I said above, simply transposing the image doesn't work, the annotations are indeed wrong.

**Comment by mona0809** [comment]
Is this problem fixed?

**Comment by zhiyoujingtian** [comment]
openimages has rotation properties


img = Image.open(img_path)
width,height = img.size

x,y,w,h = annotations['bbox']
if not img._getexif() is None:
    x = x/height*width
    y = y/width*height
    w = w/height*width
    h = h/width*height
left,top,right,bottom = [int(x) for x in [x,y,x+w,y+h]]

**Comment by zhiyoujingtian** [comment]
```
img = Image.open(img_path)
width,height = img.size
x,y,w,h = annotations['bbox']
if not img._getexif() is None:
    x = x/height*width
    y = y/width*height
    w = w/height*width
    h = h/width*height
left,top,right,bottom = [int(x) for x in [x,y,x+w,y+h]]
```

![aaaa](https://user-images.githubusercontent.com/17794133/130219926-dc2e2938-b4d0-439f-9740-5e29d9c15f93.png)

**Comment by RookieHong** [comment]
> ```
> img = Image.open(img_path)
> width,height = img.size
> x,y,w,h = annotations['bbox']
> if not img._getexif() is None:
>     x = x/height*width
>     y = y/width*height
>     w = w/height*width
>     h = h/width*height
> left,top,right,bottom = [int(x) for x in [x,y,x+w,y+h]]
> ```
> 
> ![aaaa](https://user-images.githubusercontent.com/17794133/130219926-dc2e2938-b4d0-439f-9740-5e29d9c15f93.png)

Wow, thank you!
