### ISSUE TITLE
The version of pytorch

### ISSUE THREAD

**Issue by gaowq2017** [fanq15/Few-Shot-Object-Detection-Dataset#23]
Hi@fanq15 Thank you for sharing the code! What's the version of torch and is ok in higher version? I meet some problem when import roi_pooling as follow:
![image](https://user-images.githubusercontent.com/29697367/81924616-ee02e900-9611-11ea-942e-1b08cc6a3679.png)
Thank you! best regard!

**Comment by fanq15** [comment]
The PyTorch vision is 0.4.1 and the code is not tested in the higher version. You can first try to go to the issues of https://github.com/roytseng-tw/Detectron.pytorch to find the solution. If you still can not solve it, please tell me here.
