### ISSUE TITLE
Before the RoI Pooling layer, how did the proposal boxe of support sample come from?

### ISSUE THREAD

**Issue by one23sunnyQQ** [fanq15/Few-Shot-Object-Detection-Dataset#3]
Hi,  fanq15:
   Your paper "Few-Shot Object Detection with Attention-RPN and Multi-Relation Detector".
    In Figure 4, before the RoI Pooling layer, how did the proposal boxe of support sample come from?
    Waiting for your reply soon.   :)

**Comment by fanq15** [comment]
The proposal box of the support sample is from the GT label. Because we are given the support image and boxes to detect objects in the query images.

**Comment by one23sunnyQQ** [comment]
Thank you for your reply.
