### ISSUE TITLE
bbox ordering inconsistent issue 

### ISSUE THREAD

**Issue by pppplin** [fanq15/Few-Shot-Object-Detection-Dataset#4]
Hey!

Thanks for all your efforts in putting up this dataset, it is definitely amazing! One small question: what's the order of bbox annotation? or is there an order (i.e. left, top, bottom, right in VOC) in bbox annotations? 
I'm asking this question since I found that bbox ordering seems to be inconsistent, for example, the first three annotations in test are:
index 0
bbox: [120, 80, 43, 127]
width:  500
height:  499

index 1
bbox: [0, 0, 1022, 1022]
width:  1024
height:  1024

index 2
bbox: [219, 237, 43, 120]
width:  375
height:  500

Any advice would be very much appreciated, thanks!

**Comment by fanq15** [comment]
The bounding box format is `(x_min, y_min, w, h)`.
