### ISSUE TITLE
Traceback (most recent call last):   File "train_converter.py", line 37, in <module>     assert os.path.exists(img_path) AssertionError

### ISSUE THREAD

**Issue by buaacarzp** [fanq15/Few-Shot-Object-Detection-Dataset#5]
Hello, I am honored to see this open data set, thank you.I used your code today to report this error when generating the json file:
```
Traceback (most recent call last):
  File "train_converter.py", line 37, in
    assert os.path.exists(img_path)
AssertionError
```
I printed the `key` and `value`:
```
key=0,value={'father_category': 'cosmetics', 'image_path': './all_images/part_2/train_part_e/e8/e8fe15d38a65c26b.jpg', 'image_name': 'e8fe15d38a65c26b', 'dataset': 'openimage', 'width': 1024.0, 'bbox': [393, 347, 48, 42], 'height': 719.0, 'category_name': 'lipstick'}
```
I found that there is no such folder: `part_2/train_part_e`. May I ask whether the data set I downloaded is different from the one you used when writing the code?
The folder under my part2 is:
![image](https://user-images.githubusercontent.com/43240561/75215104-a7e47900-57ca-11ea-90d8-aeb758606f6f.png)

**Comment by fanq15** [comment]
It seems that your downloaded dataset is not complete. The complate `part_2` should have `train_part_0  train_part_1  train_part_2  train_part_3	train_part_4  train_part_5  train_part_6  train_part_7	train_part_8  train_part_9  train_part_a  train_part_b	train_part_c  train_part_d  train_part_e  train_part_f`

**Comment by buaacarzp** [comment]
ok , I got it , I am changing the code now,thank you very much .
