### ISSUE TITLE
One-shot evaluation

### ISSUE THREAD

**Issue by kachiO** [fanq15/Few-Shot-Object-Detection-Dataset#8]
A few follow up questions from the paper:
- During one-shot evaluation, did you test the configuration where the support image class was not present in the query image? I ask because in Figure 4 and from the text of the paper, it seems that the global head and local heads output match scores, however I didn't see an performance evaluation of how well the model can predict whether the support class was present in the query image. 
- Table 3: I noticed that the performance with the attentional RPN was not included, what kind of performance did you observe in that configuration?

**Comment by fanq15** [comment]
Actually, in the ablation studies, we use the 5-way 5-shot evaluation as in RepMet (there is no one-shot evaluation in our paper). So there are support categories that are not in the query image. You can reference this paper.
The table 3 is only for different training strategies, and the evaluation is 5-way 5-shot. The attention RPN is evaluated in the 1-way 1-shot and 2-way 5-shot training strategies.
