### ISSUE TITLE
Question about evaluation

### ISSUE THREAD

**Issue by jhl13** [fanq15/Few-Shot-Object-Detection-Dataset#9]
Hello, fantastic job!
Two questions about evaluation. 
(1)  In the 5-shot detection scenario, you mix up all test images and for each object category, pick 5 images that contain the target object. Do you test all the remaining images to get a mAP or do you just take one image at a time as a query image and repeat it ( pick 5 images again and test another query image randomly ) multiple times?
(2) The same question applies to the  5-way 5-shot evaluation.

**Comment by fanq15** [comment]
You can reference the RepMet for the 5-way 5-shot evaluation details. We use the same evaluation protocol.
Table 6 is the 200-way evaluation where we fix the supports and evaluate all the images in the entire test set. You can treat the fixed supports as the network weights as in the conventional object detection network. The difference is that the conventional object detection network will use the softmax function to process all the categories' output, while our model outputs the foreground and background scores with sigmoid function for every category separately (there is no softmax function among categories). But they both need to process the entire test set.

**Comment by jhl13** [comment]
> You can reference the RepMet for the 5-way 5-shot evaluation details. We use the same evaluation protocol.
> Table 6 is the 200-way evaluation where we fix the supports and evaluate all the images in the entire test set. You can treat the fixed supports as the network weights as in the conventional object detection network. The difference is that the conventional object detection network will use the softmax function to process all the categories' output, while our model outputs the foreground and background scores with sigmoid function for every category separately (there is no softmax function among categories). But they both need to process the entire test set.

Thank you. So there's only one support set in the article, and it doesn't repeat sampling other support sets for multiple tests, right?

**Comment by fanq15** [comment]
For the 5-way 5-shot evaluation, there are 600 testing epochs where every testing epoch contains 5-way 5-shot supports (5 categories with 5 images per category) and corresponding 5*10 queries (5 categories with 10 images per category). In every epoch, the support will be randomly sampled only once.
For the full-way evaluation in Table 4, 5, and 6, there is only one testing epoch with one fixed support set which will evaluate the entire test set.
Is it clear?

**Comment by jhl13** [comment]
> For the 5-way 5-shot evaluation, there are 600 testing epochs where every testing epoch contains 5-way 5-shot supports (5 categories with 5 images per category) and corresponding 5*10 queries (5 categories with 10 images per category). In every epoch, the support will be randomly sampled only once.
> For the full-way evaluation in Table 4, 5, and 6, there is only one testing epoch with one fixed support set which will evaluate the entire test set.
> Is it clear?

Oh, I get it now！Thank you very much！
